CREATE TABLE sites (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand TEXT NOT NULL,
    logo TEXT NOT NULL,
    banner TEXT NOT NULL,
    seller_description TEXT NOT NULL,
    subdomain TEXT NOT NULL,
    resources INTEGER ARRAY,
    "user_id" INTEGER REFERENCES "users"(id)
    ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
)