CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_completed TIMESTAMPTZ DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    brand TEXT NOT NULL,
    p_image TEXT NOT NULL,
    price DECIMAL(5,2),
    in_stock INTEGER,
    p_description TEXT NOT NULL,
    "sites_id" INTEGER REFERENCES "sites"(id)
    ON DELETE CASCADE NOT NULL
)