INSERT INTO tastings (wineName,
      producer,
      varietal,
      vintage,
      region,
      condition,
      concentration,
      colorRed,
      colorWhite,
      colorRose,
      rim,
      extract,
      tearing,
      gas,
      conditionNose,
      intensity,
      ageAssessment,
      fruitRed,
      fruitWhite,
      fruitRose,
      sweetness,
      fruitFRed,
      fruitFWhite,
      fruitFRose,
      nonFruit,
      earth,
      mineral,
      tannins,
      acidity,
      alcohol,
      complexity,
      length,
      body,
      texture,
      woodAge,
      woodSize,
      woodOrigin,
      comments,
      score, userId)

VALUES
  ('Poliziano','Federico Carletti','Sangiovese',2017,'Montepulciano','Hazy','Medium','Ruby', null, null,true,'Heavy','Medium',true,'TCA','Moderate', 'Vinous',
 'Black',
 null,
 null,
    'Bone Dry',
   'Black, Blue',
   null,
   null,
  'Animal',
    'Mushrooms',
   'Limestone',
    'Low',
   'Medium',
    'Med+',
     'High',
     'Short',
   'Ligth',
 'Round',
   'Spectacular wine from Italy',
    'Old',
    'American',
    'Large',
  95-100, 1)
  ,
  ('Yacochuya',
    'The Etcharts',
    'Malbec',
     2007,
     'Salta Cafaye Valley',
   'Clear',
     'Pale',
    'Purple',
    null,
    null,
    false,
    'Ligth',
    'Medium',
    true,
   'None',
    'Delicate',
    'Youthful',
   'Tropical/Melon',
   null,
   null,
   'Bone Dry',
     'Red',
     null,
     null,
    'Vegetable, Spice ',
    'Compost',
    'Wet Stone',
    'High',
    'Med+',
    'Medium',
    'Med+',
    'Long',
   'Full',
   'Creamy',
   'Spectacular wine from Salta, deep red, complex and ripe fruits',
    'Old',
   'American',
    'Large',
    85-89, 2)